### ISSUE TITLE
Spacemesh Public API endpoint

### ISSUE THREAD

**Issue by avive** [spacemeshos/product#75]
# Motivation

We'd like to enable clients to get mesh and account statues and submit transactions w/o running a full node on a PC and being synced with the mesh. This is required to implement the important wallet-only-mode app feature for 0.2.

# Requirements
- Must be highly available and operationally supported as part of the sm production env.
- Should be available via https.
- Should not expose a managed bootstrap node to new attacks by introducing a new attack surface.
- Must not expose any node's management feature such as POST setup and coinbase account.

# Details
Prior to API refactoring into facades / modules we want to expose *ONLY* the following v1 api REST end points. They are categorized into categories just for conceptual purposes. 

All the methods are read-only and don't affect the node's state with the exception of submittransaction which submits a new transaction to the pool.

Whiteboard: https://github.com/spacemeshos/product/blob/master/api_v2_modeling.md
Master API design: https://github.com/spacemeshos/product/blob/master/api.md

**Comment by lrettig** [comment]
How do we control access? Whitelist allowed IP ranges via commandline flag?

**Comment by avive** [comment]
Why should we? This is public API that allows clients to read mesh data and to submit txs.
Similar to infura.

**Comment by lrettig** [comment]
To prevent DoS attacks. Infura requires you to register and use an API key.

**Comment by avive** [comment]
The project made it to the big boys league if entities start to ddos our public api endpoint.
Infura was anon w/o key for a long time until eth became popular... nobody cared...

**Comment by avive** [comment]
@ilans @noamnelke @ilans - please review the proposed API changes for sm 0.2 - we want to have the `transactions` and `accounts` API facets public on spacecraft envs asap so we can start building the wallet-only app mode - a major 0.2 app feature. I spoke about it with Ilan - each env should have a canonical endpoint for the API but we don't want to expose the Mesh api methods - only the txs and accounts ones....

**Comment by avive** [comment]
@lane - As @noamnelke mentioned - we want to add pagination support to all API methods that return a list of results and not all the results in the response - I think we already have some issues about that.

**Comment by noamnelke** [comment]
Why not expose the `mesh` endpoints?

Yesterday I learned from @ilans that nodes in Spacecraft aren’t planned to be accessible from the internet which would preclude this functionality. Maybe we should hear from him if it’s even possible.

**Comment by avive** [comment]
This is a longer term SMIP proposal. Short term spacecraft not really relevant. We can decide what API to expose on a per-api basis. Mesh might be useful as well. I'm closing this issue and moving it to the SMIP repo for review. The order of things are: 1. design the new api and implement it. 2. design the public endpoint and provide it for testnets.

**Comment by avive** [comment]
Moved to https://github.com/spacemeshos/SMIPS/issues/15
