### ISSUE TITLE
Unify wallet data format - CLIWallet and App

### ISSUE THREAD

**Issue by avive** [spacemeshos/product#81]

**Comment by lrettig** [comment]
cf. https://github.com/DaveAppleton/smesh2cli

**Comment by avive** [comment]
@IlyaVi please assign to @moshababo when the app wallet file format is finalized. e.g. it doesn't keep cached tx data.

**Comment by avive** [comment]
First step is in progress - @IlyaVi is documented the smapp wallet file format.

**Comment by lrettig** [comment]
@avive @IlyaVi could you link to the issue/PR where this is being worked on? Thanks!

**Comment by IlyaVi** [comment]
@lrettig https://github.com/spacemeshos/smapp/blob/develop/wallet-structure.md

**Comment by avive** [comment]
There's an issue for this in the CLIWallet repo and there's a smip for the file format so this issue can be closed.
